services:
  mysql-payments:
    image: mysql:8.0
    container_name: mysql-payments
    restart: always
    ports:
      - "3321:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_payments_db
    volumes:
      - mysql-payments-data:/var/lib/mysql

volumes:
  mysql-payments-data: