services:
  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    restart: always
    ports:
      - "3320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_inventory_db
    volumes:
      - mysql-inventory-data:/var/lib/mysql

volumes:
  mysql-inventory-data: