server:
  port: 8087

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:7071
  datasource:
    url: jdbc:mysql://localhost:3321/sales_payments_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs