server:
  port: 7091

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:7071
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info